apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: o2p-metadata-db
  namespace: default
spec:
  serviceName: "metadata-db"
  replicas: 1
  selector:
    matchLabels:
      app: o2p-metadata-db
  template:
    metadata:
      labels:
        app: o2p-metadata-db
    spec:
      containers:
      - name: postgres
        image: postgres:14-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "o2p_metadata"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: o2p-secrets
              key: metadata-db-password
        volumeMounts:
        - name: db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: metadata-db-service
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: o2p-metadata-db
