// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using O2P.Infrastructure.Metadata;

#nullable disable

namespace O2P.Infrastructure.Metadata.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260707140548_M6_ProductionHardening")]
    partial class M6_ProductionHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("o2p")
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("dataprotection_keys", "o2p");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", "o2p");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", "o2p");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", "o2p");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "o2p");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.Application", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("applications", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ApplicationConnection", b =>
                {
                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Slot")
                        .HasColumnType("text");

                    b.Property<long>("ConnectionId")
                        .HasColumnType("bigint");

                    b.HasKey("ApplicationId", "Slot");

                    b.HasIndex("ConnectionId");

                    b.ToTable("application_connections", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ChunkLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<long>("BytesMigrated")
                        .HasColumnType("bigint");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EndRowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("RowsMigrated")
                        .HasColumnType("bigint");

                    b.Property<string>("StartRowId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TableRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeaseExpiresAt");

                    b.HasIndex("Status");

                    b.HasIndex("TableRunId");

                    b.HasIndex("WorkerId");

                    b.ToTable("chunk_logs", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.Connection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<int>("Port")
                        .HasColumnType("integer");

                    b.Property<byte[]>("SecretCiphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ServiceOrDb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("connections", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.DiscoveryCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ConnectionId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsIot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPartitioned")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastRefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LobBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("NumRows")
                        .HasColumnType("bigint");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("SegmentBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ConnectionId", "Owner", "TableName")
                        .IsUnique();

                    b.ToTable("discovery_cache", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.DiscoveryColumnCache", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<int>("ColumnId")
                        .HasColumnType("integer");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DataLength")
                        .HasColumnType("integer");

                    b.Property<int?>("DataPrecision")
                        .HasColumnType("integer");

                    b.Property<int?>("DataScale")
                        .HasColumnType("integer");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("DiscoveryCacheId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsIdentity")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryCacheId", "ColumnName")
                        .IsUnique();

                    b.ToTable("discovery_column_cache", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.JobCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Command")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IssuedBy")
                        .HasColumnType("text");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Payload")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.ToTable("JobCommands", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.JobRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ManifestId")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetSchema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetSlot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ManifestId");

                    b.HasIndex("Status");

                    b.ToTable("job_runs", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.Manifest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("manifests", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestColumn", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNullable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimaryKey")
                        .HasColumnType("boolean");

                    b.Property<long>("ManifestTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("OracleDataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostgresDataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManifestTableId", "ColumnName")
                        .IsUnique();

                    b.ToTable("manifest_columns", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Columns")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IndexType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsUnique")
                        .HasColumnType("boolean");

                    b.Property<long>("ManifestTableId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ManifestTableId", "IndexName")
                        .IsUnique();

                    b.ToTable("manifest_indexes", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("EstBytes")
                        .HasColumnType("bigint");

                    b.Property<long?>("EstRows")
                        .HasColumnType("bigint");

                    b.Property<string[]>("ExcludedColumns")
                        .HasColumnType("text[]");

                    b.Property<bool>("HasLobs")
                        .HasColumnType("boolean");

                    b.Property<bool>("Included")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsIot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPartitioned")
                        .HasColumnType("boolean");

                    b.Property<long>("ManifestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhereClause")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManifestId");

                    b.ToTable("manifest_tables", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.MetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ActiveChunkWorkers")
                        .HasColumnType("integer");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint");

                    b.Property<double>("MbPerSecond")
                        .HasColumnType("double precision");

                    b.Property<int>("OracleSessions")
                        .HasColumnType("integer");

                    b.Property<double>("RowsPerSecond")
                        .HasColumnType("double precision");

                    b.Property<long?>("TableRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("TableRunId");

                    b.ToTable("MetricSamples", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.RowReject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChunkLogId")
                        .HasColumnType("bigint");

                    b.Property<string>("ColumnName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceRowId")
                        .HasColumnType("text");

                    b.Property<long>("TableRunId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ChunkLogId");

                    b.HasIndex("TableRunId");

                    b.ToTable("row_rejects", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.RunEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("JobRunId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.HasIndex("JobRunId");

                    b.ToTable("run_events", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.RunLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("ChunkLogId")
                        .HasColumnType("bigint");

                    b.Property<long?>("JobRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("TableRunId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("JobRunId");

                    b.HasIndex("Timestamp");

                    b.ToTable("run_logs", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.TableRun", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long>("BytesMigrated")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<long>("JobRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("ManifestTableId")
                        .HasColumnType("bigint");

                    b.Property<long>("RowsMigrated")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetTableName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ManifestTableId");

                    b.HasIndex("Status");

                    b.HasIndex("JobRunId", "TargetTableName")
                        .IsUnique();

                    b.ToTable("table_runs", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.TargetNameAllocation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SchemaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SuffixNumber")
                        .HasColumnType("integer");

                    b.Property<long>("TableRunId")
                        .HasColumnType("bigint");

                    b.Property<long>("TargetConnectionId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TableRunId")
                        .IsUnique();

                    b.HasIndex("TargetConnectionId", "SchemaName", "BaseName", "SuffixNumber")
                        .IsUnique();

                    b.ToTable("target_name_allocations", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.TypeMappingRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApplicationId")
                        .HasColumnType("bigint");

                    b.Property<string>("ColumnName")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("ManifestTableId")
                        .HasColumnType("bigint");

                    b.Property<string>("MatchJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "ApplicationId", "ManifestTableId", "ColumnName");

                    b.ToTable("type_mapping_rules", "o2p");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ValidationResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColumnName")
                        .HasColumnType("text");

                    b.Property<string>("DetailJson")
                        .HasColumnType("text");

                    b.Property<bool>("Passed")
                        .HasColumnType("boolean");

                    b.Property<string>("SourceValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("TableRunId")
                        .HasColumnType("bigint");

                    b.Property<string>("TargetValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TableRunId");

                    b.ToTable("ValidationResults", "o2p");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2P.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("O2P.Domain.Entities.ApplicationConnection", b =>
                {
                    b.HasOne("O2P.Domain.Entities.Application", "Application")
                        .WithMany("Connections")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2P.Domain.Entities.Connection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ChunkLog", b =>
                {
                    b.HasOne("O2P.Domain.Entities.TableRun", "TableRun")
                        .WithMany("Chunks")
                        .HasForeignKey("TableRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableRun");
                });

            modelBuilder.Entity("O2P.Domain.Entities.DiscoveryCache", b =>
                {
                    b.HasOne("O2P.Domain.Entities.Connection", "Connection")
                        .WithMany()
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Connection");
                });

            modelBuilder.Entity("O2P.Domain.Entities.DiscoveryColumnCache", b =>
                {
                    b.HasOne("O2P.Domain.Entities.DiscoveryCache", "DiscoveryCache")
                        .WithMany("Columns")
                        .HasForeignKey("DiscoveryCacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiscoveryCache");
                });

            modelBuilder.Entity("O2P.Domain.Entities.JobCommand", b =>
                {
                    b.HasOne("O2P.Domain.Entities.JobRun", "JobRun")
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRun");
                });

            modelBuilder.Entity("O2P.Domain.Entities.JobRun", b =>
                {
                    b.HasOne("O2P.Domain.Entities.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2P.Domain.Entities.Manifest", "Manifest")
                        .WithMany()
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("O2P.Domain.Entities.Manifest", b =>
                {
                    b.HasOne("O2P.Domain.Entities.Application", "Application")
                        .WithMany("Manifests")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestColumn", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ManifestTable", "ManifestTable")
                        .WithMany("Columns")
                        .HasForeignKey("ManifestTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManifestTable");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestIndex", b =>
                {
                    b.HasOne("O2P.Domain.Entities.ManifestTable", "ManifestTable")
                        .WithMany("Indexes")
                        .HasForeignKey("ManifestTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManifestTable");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestTable", b =>
                {
                    b.HasOne("O2P.Domain.Entities.Manifest", "Manifest")
                        .WithMany("Tables")
                        .HasForeignKey("ManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manifest");
                });

            modelBuilder.Entity("O2P.Domain.Entities.MetricSample", b =>
                {
                    b.HasOne("O2P.Domain.Entities.JobRun", "JobRun")
                        .WithMany()
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2P.Domain.Entities.TableRun", "TableRun")
                        .WithMany()
                        .HasForeignKey("TableRunId");

                    b.Navigation("JobRun");

                    b.Navigation("TableRun");
                });

            modelBuilder.Entity("O2P.Domain.Entities.TableRun", b =>
                {
                    b.HasOne("O2P.Domain.Entities.JobRun", "JobRun")
                        .WithMany("TableRuns")
                        .HasForeignKey("JobRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("O2P.Domain.Entities.ManifestTable", "ManifestTable")
                        .WithMany()
                        .HasForeignKey("ManifestTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobRun");

                    b.Navigation("ManifestTable");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ValidationResult", b =>
                {
                    b.HasOne("O2P.Domain.Entities.TableRun", "TableRun")
                        .WithMany()
                        .HasForeignKey("TableRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableRun");
                });

            modelBuilder.Entity("O2P.Domain.Entities.Application", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Manifests");
                });

            modelBuilder.Entity("O2P.Domain.Entities.DiscoveryCache", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("O2P.Domain.Entities.JobRun", b =>
                {
                    b.Navigation("TableRuns");
                });

            modelBuilder.Entity("O2P.Domain.Entities.Manifest", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("O2P.Domain.Entities.ManifestTable", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Indexes");
                });

            modelBuilder.Entity("O2P.Domain.Entities.TableRun", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
